name: personal_blog
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.4.0
  carousel_slider: ^5.0.0
  pocketbase: ^0.17.1
  media_kit: ^1.1.10+1
  motion_toast: ^2.8.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  ffmpeg_kit_flutter_audio: ^6.0.3
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.3.0
  gap: ^3.0.1
  media_scanner: ^2.1.0
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.10+1
  youtube_explode_dart: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/images/
    - assets/images/apple_image2.svg

fonts:
  - family: Pretendard
    fonts:
      - asset: assets/fonts/Pretendard-Thin.ttf
        weight: 100
      - asset: assets/fonts/Pretendard-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Pretendard-Light.ttf
        weight: 300
      - asset: assets/fonts/Pretendard-Regular.ttf
        weight: 400
      - asset: assets/fonts/Pretendard-Medium.ttf
        weight: 500
      - asset: assets/fonts/Pretendard-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Pretendard-Bold.ttf
        weight: 700
      - asset: assets/fonts/Pretendard-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Pretendard-Black.ttf
        weight: 900
